# Generated by Django 6.0.1 on 2026-02-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsubject',
            name='teacher',
        ),
    ]
